### ISSUE TITLE
Publishing release 2.0.7 into the Jenkins Update Center

### ISSUE THREAD

**Issue by jheilgeist** [jenkinsci/prometheus-plugin#149]
Hi,

the latest version of the prometheus-plugin available in the Jenkins update center, e.g., at https://updates.jenkins.io/latest/prometheus.hpi, is still the previous release 2.0.6. Can you please publish the latest release 2.0.7?

We need the fix for the StackOverflowError from #127, but are required by company policy to only use plugin versions officially published into the update center.

Thanks,
Janko

@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
Yes, this is a known problem and I am working through it. Update to follow

**Comment by justfalter** [comment]
Any update on this? It looks like updates.jenkins.io is still serving 2.0.6.

**Comment by markyjackson-taulia** [comment]
Will be done this week

**Comment by Snapstromegon** [comment]
Any updates?

**Comment by ncoyne** [comment]
This is currently a blocker for me as well.

**Comment by markyjackson-taulia** [comment]
Hope to have it out there this weekend

**Comment by ncoyne** [comment]
Are there any updates on when we can expect this? Or what is holding the process up? Thanks!

**Comment by markyjackson-taulia** [comment]
@ncoyne and all others,
Time is holding the process. We have a very large regression with releasing the core update and that took a lot of time. I will hopefully get this out this week. In the meantime, you can also compile the hpi from source so you are not totally blocked

**Comment by MattLuceen** [comment]
My organization is also patiently awaiting the 2.0.7 release in Jenkins 😃

**Comment by markyjackson-taulia** [comment]
Plan is this weekend @MattLuceen

**Comment by kisoku** [comment]
@markyjackson-taulia is there anything we can to do to help speed up the process of getting an official release of 2.0.7 ?

**Comment by markyjackson-taulia** [comment]
There were issues with the artifact deployment that were fixed yesterday by the infra team. I will release his Friday evening

**Comment by chesney** [comment]
@markyjackson-taulia I hope you're doing well. Any update on the last deployment? Thanks

**Comment by markyjackson-taulia** [comment]
> @markyjackson-taulia I hope you're doing well. Any update on the last deployment? Thanks

I am working with the Jenkins infra team on this. Will have an update tomorrow

**Comment by joelee2012** [comment]
@markyjackson-taulia  any updates for this ?

**Comment by mwolniewicz** [comment]
@markyjackson-taulia any update on the issue? It's been almost a month since your last update and the plugin is still not released.

**Comment by chesney** [comment]
@markyjackson-taulia I hope all is well your side. Do you perhaps have any update on this issue, seems the community are waiting with bated breath for the next release ( myself included ) Thanks

**Comment by MattLuceen** [comment]
@markyjackson-taulia Anything the community can do to help?

**Comment by mechaHarry** [comment]
office_skeleton.jpg

**Comment by markyjackson-taulia** [comment]
Release will go out this weekend. Doing my best here y’all. You have the ability to build the .hpi

**Comment by andreatera** [comment]
ehi guys, any update on this?

**Comment by markyjackson-taulia** [comment]
Better later than never I guess. It should be in the update center in an hour or so.
Let me explain what happened here so there is no confusion and I am fully transparent.
1. Covid-19
2. Massive world-chaos
3. Change in jobs derailed a lot for me
4. I had to take a mental break due to personal issues.

I love open-source and have been a part of it for many years. The above items weighed on me heavily due to my love for open-source so I deeply apologies for the flakiness, that is not my MO.

Much love to all and I hope each and every one of you is safe and well.

```
    Uploading to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/prometheus/2.0.7/prometheus-2.0.7-javadoc.jar
    Uploaded to maven.jenkins-ci.org: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/prometheus/2.0.7/prometheus-2.0.7-javadoc.jar (496 kB at 437
```
